name: on-push-build-test-and-run-application

on: push

permissions:
  id-token: write
  contents: read

jobs:
  build-test-and-run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - name: Setup Go 1.21.0
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'

      - name: Test
        run: go test ./...

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o go-test-summary .

      - name: Run go-test-summary
        run: go run ./main.go
